import img1 from '../assets/tabla rigida.jpg'
import img2 from '../assets/collarcervicalplano.jpg'
import img3 from '../assets/collar cervical con orificio traqueal.jpg'
import img4 from '../assets/inmovilizador lateral.jpg'
import img5 from '../assets/colchon vacio.jpg'
import img6 from '../assets/camilla canasta.jpg'
import img7 from '../assets/camilla plegable.jpg'
import img8 from '../assets/cincha pelvica.jpg'
import img9 from '../assets/set ferulas.jpg'
import img10 from '../assets/torniquete tactico.jpg'
import img11 from '../assets/combat gauze.jpg'
import img12 from '../assets/aspirador manual.jpg'
import img13 from '../assets/ambu adulto.jpg'
import img14 from '../assets/canula guedel.jpg'
import img15 from '../assets/mascara laringea.jpg'
import img16 from '../assets/pinza maguil.jpg'
import img18 from '../assets/set tet.jpg'

export default (img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12,img13, img14, img15, img16, img17, img18)