// import img1 from '../assets/tablarigida.jpg'
// import img2 from '../assets/collarcervicalplano.jpg'
// import img3 from '../assets/collarorificiotraqueal.jpg'
// import img4 from '../assets/inmovilizadorlateral.jpg'
// import img5 from '../assets/colchonvacio.jpg'
// import img6 from '../assets/camillacanasta.jpg'
// import img7 from '../assets/camillaplegable.jpg'
// import img8 from '../assets/cinchapelvica.jpg'
// import img9 from '../assets/setferulas.jpg'
// import img10 from '../assets/torniquetetactico.jpg'
// import img11 from '../assets/combatgauze.jpg'
// import img12 from '../assets/aspiradormanual.jpg'
// import img13 from '../assets/ambuadulto.jpg'
// import img14 from '../assets/canguedel.jpg'
// import img15 from '../assets/masclaringea.jpg'
// import img16 from '../assets/pinzamaguil.jpg'
// import img18 from '../assets/settet.jpg'
// import img19 from '../assets/reboa.jpg'

// export default (img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12,img13, img14, img15, img16, img17, img18, img19)